import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { txnTitle, txnAmount, fmt } from '@/components/TxnRow';
import type { LedgerTransaction } from '@/services/api';

const STATUS_COLOR: Record<string, string> = {
  COMPLETED: '#34C759',
  PENDING: '#F5A623',
  PROCESSING: '#F5A623',
  FAILED: '#EF4444',
  REVERSED: '#EF4444',
};

function esc(s: string): string {
  return s.replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c] as string));
}

function rows(tx: LedgerTransaction): Array<[string, string, boolean]> {
  const out: Array<[string, string, boolean]> = [];
  out.push(['Type', tx.type, false]);
  out.push(['Date', new Date(tx.createdAt).toLocaleString('en-NG'), false]);
  if (tx.fromFormatted && tx.toFormatted) {
    out.push(['From', `${fmt(tx.fromFormatted)} ${tx.fromAsset}`, false]);
    out.push(['To', `${fmt(tx.toFormatted)} ${tx.toAsset}`, false]);
  }
  if (tx.rate) out.push(['Rate', tx.rate, false]);
  if (tx.network) out.push(['Network', tx.network, false]);
  if (tx.billerName) out.push(['Biller', tx.billerName, false]);
  if (tx.planName) out.push(['Plan', tx.planName, false]);
  if (tx.customer) out.push(['Recipient', tx.customer, false]);
  if (Number(tx.feeFormatted) > 0) out.push(['Fee', `${fmt(tx.feeFormatted)} ${tx.asset}`, false]);
  if (tx.toAddress) out.push(['Address', tx.toAddress, true]);
  if (tx.txHash) out.push(['Transaction hash', tx.txHash, true]);
  out.push(['Reference', tx.id, true]);
  return out;
}

/** Branded HTML receipt rendered to PDF by expo-print. */
export function receiptHtml(tx: LedgerTransaction): string {
  const amt = txnAmount(tx);
  const status = STATUS_COLOR[tx.status] ?? '#9A93AD';
  const rowsHtml = rows(tx)
    .map(
      ([label, value, mono]) => `
        <tr>
          <td class="label">${esc(label)}</td>
          <td class="value${mono ? ' mono' : ''}">${esc(value)}</td>
        </tr>`
    )
    .join('');

  return `<!DOCTYPE html><html><head><meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    * { box-sizing: border-box; font-family: -apple-system, Roboto, Helvetica, Arial, sans-serif; }
    body { margin: 0; padding: 0; color: #14121A; }
    .header { background: #6B5B95; color: #fff; padding: 40px; text-align: center; }
    .brand { font-size: 30px; font-weight: 800; letter-spacing: -0.5px; }
    .brand .q { color: #F5C97B; }
    .sub { opacity: .85; margin-top: 6px; font-size: 13px; }
    .body { padding: 36px 40px; }
    .amount { text-align: center; margin-bottom: 8px; font-size: 40px; font-weight: 800; color: ${amt.positive ? '#159A4B' : '#14121A'}; }
    .title { text-align: center; color: #6b6b73; font-size: 16px; }
    .pill { display: inline-block; margin: 14px auto 0; padding: 6px 16px; border-radius: 999px; font-size: 13px; font-weight: 700; color: ${status}; background: ${status}22; }
    .center { text-align: center; }
    table { width: 100%; border-collapse: collapse; margin-top: 30px; }
    td { padding: 13px 0; border-top: 1px solid #ECEAF1; font-size: 14px; vertical-align: top; }
    .label { color: #8b8b93; width: 42%; }
    .value { text-align: right; font-weight: 600; }
    .mono { font-family: 'Courier New', monospace; word-break: break-all; font-size: 12px; }
    .footer { text-align: center; color: #a0a0a8; font-size: 12px; padding: 28px 40px 40px; }
  </style></head>
  <body>
    <div class="header">
      <div class="brand">Cheq<span class="q">Pay</span></div>
      <div class="sub">Transaction receipt</div>
    </div>
    <div class="body">
      <div class="amount">${esc(amt.text)}</div>
      <div class="title">${esc(txnTitle(tx))}</div>
      <div class="center"><span class="pill">${esc(tx.status)}</span></div>
      <table>${rowsHtml}</table>
    </div>
    <div class="footer">Generated by CheqPay · cheqpay.app<br/>Keep this receipt for your records.</div>
  </body></html>`;
}

/** Build a branded PDF and open the native share sheet. */
export async function shareReceipt(tx: LedgerTransaction): Promise<void> {
  const { uri } = await Print.printToFileAsync({ html: receiptHtml(tx), base64: false });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: 'Share receipt',
      UTI: 'com.adobe.pdf',
    });
  }
}
